"use client";
import { FormEvent, useState } from "react";

export default function InquiryForm({ initialProduct="", initialType="Produkt" }: { initialProduct?: string; initialType?: string }) {
  const [ready,setReady]=useState(false); const [data,setData]=useState({name:"",company:"",phone:"",email:"",city:"",type:initialType,product:initialProduct,message:"",consent:false,website:""});
  function update(name:string,value:string|boolean){setReady(false);setData(d=>({...d,[name]:value}))}
  function submit(e:FormEvent){e.preventDefault(); if(data.website)return; setReady(true)}
  const text=encodeURIComponent(`Përshëndetje, jam ${data.name}${data.company?` nga ${data.company}`:""}.\nLloji: ${data.type}\nProdukti: ${data.product||"Nuk është zgjedhur"}\nQyteti: ${data.city}\nTelefoni: ${data.phone}\n${data.message}`);
  return <form className="inquiryForm" onSubmit={submit}><div className="formGrid"><label>Emri dhe mbiemri *<input required value={data.name} onChange={e=>update("name",e.target.value)} placeholder="Shkruani emrin" /></label><label>Kompania <input value={data.company} onChange={e=>update("company",e.target.value)} placeholder="Emri i kompanisë" /></label><label>Telefoni *<input required type="tel" value={data.phone} onChange={e=>update("phone",e.target.value)} placeholder="+383 ..." /></label><label>Email <input type="email" value={data.email} onChange={e=>update("email",e.target.value)} placeholder="email@kompania.com" /></label><label>Qyteti *<input required value={data.city} onChange={e=>update("city",e.target.value)} placeholder="Qyteti" /></label><label>Lloji i kërkesës<select value={data.type} onChange={e=>update("type",e.target.value)}><option>Produkt</option><option>Ofertë biznesi</option><option>Dokumentacion teknik</option><option>Tjetër</option></select></label><label className="full">Produkti<input value={data.product} onChange={e=>update("product",e.target.value)} placeholder="Emri ose grada e produktit — opsionale" /></label><label className="full">Mesazhi *<textarea required rows={5} value={data.message} onChange={e=>update("message",e.target.value)} placeholder="Na tregoni automjetin, pajisjen ose specifikimin që kërkoni" /></label><label className="honeypot" aria-hidden="true">Website<input tabIndex={-1} autoComplete="off" value={data.website} onChange={e=>update("website",e.target.value)} /></label></div><label className="consent"><input required type="checkbox" checked={data.consent} onChange={e=>update("consent",e.target.checked)} /> Pajtohem që të dhënat e mia të përdoren vetëm për t’iu përgjigjur kësaj kërkese.</label><button className="button primary submitButton" type="submit">Përgatit kërkesën <span>→</span></button>{ready&&<div className="formReady" role="status"><strong>Kërkesa është gati.</strong><p>Zgjidhni kanalin për ta dërguar. Faqja nuk ruan të dhënat tuaja.</p><div><a className="button primary" href={`https://wa.me/38344303130?text=${text}`}>Dërgo në WhatsApp ↗</a><a className="button ghost" href={`mailto:besiana.llc@gmail.com?subject=${encodeURIComponent(`Kërkesë CYCLON — ${data.type}`)}&body=${text}`}>Dërgo me email ↗</a></div></div>}</form>
}
